### ISSUE TITLE
TextField value does not update if text changes but parsed value remains the same (removing decimal zeroes does not update format)

### ISSUE THREAD

**Issue by marceliwac** [jbadger3/TextFieldBehavior#1]
Thanks for a great repository and the blog post, it's been very helpful so far! Unfortunately, even though it is now 2024, there still seems to be a need for this approach when using numbers with `TextField`s in SwiftUI...

I've tried using your code in my application which formats doubles to always display 2 decimal places:
```swift
let f = NumberFormatter() 
f.numberStyle = .decimal
f.minimumFractionDigits = 2
```

Things work almost perfectly well, except when changing the `TextField`'s value in a way which doesn't alter the actual number (e.g. `"10.00"` -> `"10"` or `"10.00"` -> `"10.0"`). In these cases, the `NumericTextField` ignores the change and does not update the format after the textfield loses focus.

I realise it's been a while, but I was wondering if you have any advice how to patch this.

_Note: Everything else works fine, for example: changing `"10.00"` -> `"11"` updates the `TextField`'s value to `"11.00"` accordingly._

**Comment by jbadger3** [comment]
Thanks for the feedback and comments!  Surprised that post still has relevance.  I did a quick review of my old code and found out I the underlying TextField.text wasn't being updated after textFieldDidEndEditing was called.  There is updated code with a fix:)

**Comment by marceliwac** [comment]
Thanks for that! Tremendous work!
